version: 2

references:

  docker_login: &docker_login
    run:
      name: Login to Docker.
      command: |
        sudo docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}

  build_x86_images: &build_x86_images
    run:
      name: Build all our x86 images.
      command: |
        # Enable Docker experimental features.
        echo '{ "experimental": true }' | sudo tee /etc/docker/daemon.json
        sudo service docker restart
        # Build images.
        cd ./dockerfiles
        ./build.sh
      no_output_timeout: 20m

jobs:

  build:
    machine: true
    working_directory: ~/dockerfiles
    steps:
      - checkout
      - *docker_login
      - *build_x86_images

workflows:
  version: 2

  test_matrix: &test_matrix
    jobs:
      - build

  weekly:
    triggers:
      - schedule:
          cron: "48 1 * * 6"
          filters:
            branches:
              only:
                - master
    <<: *test_matrix

