FROM archlinux/base
MAINTAINER Iterait a.s. <docker@iterait.com>

# install common packages
RUN pacman --noconfirm --needed -Syu \
      base-devel \
      vim \
    && pacman -Rdd --noconfirm guile

ENV EDITOR vim

CMD ["/bin/bash"]
