FROM iterait/archlinuxarm
LABEL thanksto "archimg/archlinux"
LABEL maintainer "Iterait a.s. <docker@iterait.com>"

# install base-devel & remove useless stuff
RUN pacman --noconfirm -Syu --needed \
        base-devel \
        cmake \
        vim \
	python \
	python-pip \
    && find /usr/lib/guile -name "*.go" | xargs rm

ENV EDITOR vim

CMD ["/bin/bash"]
