#!/bin/sh
# Also push with versioned tag.
TIMESTAMP="$(date -u +%Y-%m-%d)"
if [ "${DOCKER_TAG}" = "latest" ]; then
    VERSION_TAG="${TIMESTAMP}"
else
    VERSION_TAG="${DOCKER_TAG}"_"${TIMESTAMP}"
fi
docker tag "${IMAGE_NAME}" "${DOCKER_REPO}":"${VERSION_TAG}"
docker push "${DOCKER_REPO}":"${VERSION_TAG}"
