name: Docker Images Build

on:
  schedule:
    - cron:  '0 21 * * *'
  push:
    branches:
      - 'master'
  workflow_dispatch:

jobs:
  build_archlinux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build-push-image
        with:
          imgname: archlinux
          build_cuda: true
          dockerhub_token_user: ${{ secrets.DOCKERHUB_TOKEN_USER }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  build_archlinux-dev:
    needs: build_archlinux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build-push-image
        with:
          imgname: archlinux-dev
          build_cuda: true
          dockerhub_token_user: ${{ secrets.DOCKERHUB_TOKEN_USER }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  build_arch-freeze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build-push-image
        with:
          imgname: arch-freeze
          build_cuda: false
          dockerhub_token_user: ${{ secrets.DOCKERHUB_TOKEN_USER }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}

  build_arch-freeze-dev:
    needs: build_arch-freeze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        uses: ./.github/actions/build-push-image
        with:
          imgname: arch-freeze-dev
          build_cuda: false
          dockerhub_token_user: ${{ secrets.DOCKERHUB_TOKEN_USER }}
          dockerhub_token: ${{ secrets.DOCKERHUB_TOKEN }}
